name: Build and release neocarta to PyPI

on:
  release:
    types: [published]
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  release:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/neocarta-v')
    environment:
      name: pypi
      url: https://pypi.org/project/neocarta/
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Build
        run: uv build

      - name: Smoke test
        run: uv run --isolated --no-project --with dist/*.whl --with pytest pytest tests/smoke/

      - name: Publish
        run: uv publish
